# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

stages:
    - test
    - build
    - deploy

"Test Node 10.15":
    stage: test
    image: node:10.15
    script:
        - npm install
        - npm run build
        - npm test
    tags:
        - node
        - test
    only:
        - testing
    cache:
        key: node-10.15
        paths:
            - node_modules/

"Lint":
    stage: test
    image: node:10.15
    script:
        - npm install
        - npm run lint
    tags:
        - node
        - test
    only:
        - testing
    cache:
        key: node-10.15
        paths:
            - node_modules/

"Deploy To LPM":
    stage: deploy
    script:
        - npm install
        - npm run build
        - npm-cli-login -u $LPM_USERNAME -p $LPM_PASSWORD -e $LPM_EMAIL -r $LPM_REGISTRY
        - npm publish --registry $LPM_REGISTRY
    only:
        - master
    cache:
        key: node-10.15-build
        paths:
            - node_modules/
    tags:
        - docker
        - deploy

pages:
    stage: build
    image: node:10.15-slim
    script:
        - npm install
        - npm run docs
        - mv ./docs public
    artifacts:
        paths:
            - public
    cache:
        key: install_cache
        paths:
            - node_modules
    environment:
        name: documentation
        url: https://lpm.pages.labx.com/image-generator/
    only:
        - master
    tags:
        - docker
        - build

